# Generated by Django 4.2.5 on 2023-09-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_test_app_3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_update',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
