# Generated by Django 4.2.5 on 2023-09-23 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_test_app_2', '0003_publication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=1000)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(default=models.DateTimeField(auto_now_add=True))),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_test_app_2.autor')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_test_app_2.publication')),
            ],
        ),
    ]
